name: Descarga precio de hoy

on:
  workflow_dispatch:
  schedule:
    - cron: 10,40 6,7,8,9,10,11,12 * * *

env:
  GASOLINA_CHAT_ID: ${{ secrets.GASOLINA_CHAT_ID }}
  DIESEL_CHAT_ID: ${{ secrets.DIESEL_CHAT_ID }}
  TOKEN_TELEGRAM: ${{ secrets.TOKEN_TELEGRAM }}
  FUEL_STATION_ID: 10298

jobs:
  downloadStatus:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js version 16.x
      uses: actions/setup-node@v1
      with:
        node-version: 16.x
    - run: npm install
    - run: npm run download-today
    - run: |
        git config user.name "Alejandro Serrano"
        git config user.email alejandroserranonotivoli@gmail.com
        git add .
        git commit -m "Add report for today"
        git push
    - run: npm run send
